### ISSUE TITLE
[BUG] - respect message edits and deletes

### ISSUE THREAD

**Issue by jaspermayone** [thepurplebubble/magic-mirror#8]
### What bug did you encounter?

respect message edits

### What did you expect to happen?

respect message edits

**Comment by jaspermayone** [comment]
and deletes!

**Comment by taciturnaxolotl** [comment]
edits are currently opperational!

**Comment by taciturnaxolotl** [comment]
only in top level messages though; respecting that in threads would require a db of every message ever sent which isn't feasible

**Comment by jaspermayone** [comment]
@kcoderhtml we can make this happen now I think no?

**Comment by jaspermayone** [comment]
edits do work you say?
